cluster:
  api-base: "YOUR_DISCOVERY_URL"
  discovery-token: "YOUR_CLUSTER_DISCOVERY_TOKEN"
  name: "YOUR_CLUSTER_NAME"
  viridian-id: "YOUR_CLUSTER_ID"
ssl:
  ca-path: "ca.pem"
  cert-path: "cert.pem"
  key-password: "YOUR_SSL_PASSWORD"
  key-path: "key.pem"

